services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python /app/manage.py runserver 0.0.0.0:8080"